<h2>Full Biography</h2><br />
<h3 class="releaseTitleText">2000 - 2004</h3>
	<section class="justified postText">
		<p>Aftershock, as the band was called back then, was formed in January 2000 by Juha Untinen and Tero Konola, after a successful band rehearsal session in the garage of Juha's cousin. Originally it was all about learning how to play loud instruments and making them form desirable noise. That quickly led to writing original music and recording it, so that everyone could hear what the fuss was all about. After it came to light that there already were several bands called Aftershock, it was clear that a new name was needed. Paying some tribute to their favourite audio editor, Sound Forge, the band was reborn as Sound Ogre. The first year of the band amounted to a total of three demos, including a wide variety of songs. Incidentally, some of them appeared on the local music charts of then-popular www.mp3.com, concluding the year in the forming of a nice little following for the band.</p>
		<p>The year 2001 was mostly spent rehearsing in the aforementioned garage, and later in the basement of Tero's home. During this time, a few new songs were composed, and were later featured on the first EP, Extinct, in almost the same form as they were originally conceived. The year was finished off with a three-song live performance at the local "Kevari" music exhibition at Club Jesperi, a very active live club at that time, in Tornio, Finland. For this show, the duo was joined by Samuli Tarvainen on bass guitar duties. The show itself went well, and the group got their live feet wet in a thoroughly enjoyable manner.</p>
		<p>The next year and a half was a little bit quieter, save for a few rehearsals with Rami Moilanen on drums and Tero on bass, in a decidedly remote location in the forests of Tornio. After some inactivity, two new songs were written in the summer of 2002, but the tracks led to nothing further in the timeline. During this time period, Tero started to work on his other band, Kollapse, with his friend Mikko Nurmos (who would later appear on the 2008 release, Deep Beneath) and they soon founded the grindcore ensemble called Relativity. With everything quiet in the Sound Ogre front, Juha joined Relativity in early 2004.</p>
		<p>In late 2004, after an extended radio silence, it was time to resume the work with Sound Ogre in earnest. This also turned out to be a time of major advances in production quality for the band. With the newly acquired skills, what better way to practice than to put the bag of tricks into use by working on some older Sound Ogre songs and bring them up-to-date. The ultimate result was the release of the band's first EP, Extinct, which was released in October 2004 through Mikseri.net. The EP features a selection of the most popular Sound Ogre demo tracks with the songs sporting an all-new structure.</p>
		<p>With the accumulated experience from making the EP, the first new Sound Ogre material in almost 3 years appeared in demo form. The songwriting flow had been unleashed with a new direction towards a more progressive sound. More songs were finished in quick order and posted at Mikseri.net for feedback. Finally, a total of six new songs were finished and eventually released as the EP-shaped collection of songs called Asphyxiation in March 2005.</p>
	</section>
<h3 class="releaseTitleText">2005 - 2009</h3>
	<section class="justified postText">
		<p>At this point, it was quite evident that Sound Ogre no longer was what it used to be. The overall sound of the band had become markedly different from the original style. This, factored with Tero's departure, meant it was time to refresh the name of the band to better represent this new direction. A certain word turned up in a Cubanate song duo. Their 1994 album, Cyberia, contained two outstanding tracks called Vortech I and Vortech II. Due the songs being quite much in line with the new mood of the band, and representing the energetically electronic style, Vortech was born in late fall of 2005. Later, it would turn out that the word came from a car part manufacturer, but apparently they don't mind the coincidence. How about that? Turbochargers and the band fit together quite well ;)</p>
		<p>So, what do you do when you have a fresh new table to start from? Why, you start writing new songs! In late 2005, during the last weeks of Juha's military service in the Finnish Defence Forces, four thrash metal flavoured songs were written, all which would be featured on the first full length release. In addition to them, another four heavier pieces and two electronic music influenced tracks were composed, bring together all the material needed for Conclusion, which was released in April 2006. With it came some changes in the songwriting methods too, as all the songs were recorded and mixed with Cubase - an important step up from the previous ways to record!</p>
		<p>As the ball had started to roll, it was no time to twiddle thumbs! Hence the work for the next full length album began, just two months after the release of Conclusion. A healthy amount of songs were written during the following six months, with ten of them making it to the final recording sessions. With newfound inspiration for music, Juha also joined the local death metal outfit, Coldway. This would also mark the first time Juha met Ville Miinala - then drummer for Coldway - who would start drumming for Vortech four years later.</p>
		<p>	By the end of the year, it was time to start recording the second full length album, and the process began in December 2006. The songs were recorded at Juha's home studio, Liberty Street Studios, over a period of two months. Following the completion of the recording, all lyrics for the album were written, during one of the coldest winters in a long time. Unfortunately, when it came time to record the vocals for the album, things didn't quite work out as planned. A long time passed before the album finally had vocals for the songs. The majority of the vocals were ultimately done by Matti Särkimäki at his home studio in Oulu. He would also go on to join the band quite soon. With all vocal parts finally ready, it was time to finish up the album. The second full length, Wasteland, was released in September 2007.</p>
		<p>With a vast array of new songs written during the vocal recording sessions for Wasteland, the next full length album was completed in a much quicker order! The main instrument tracking started less than 2 months after the release of Wasteland, and all the lyrics were written between December 2007 and January 2008. With Matti now a member of the band, the band started recording the vocals for the album at the Siwa Studios (rehearsal space of Relativity) in the end of February 2008. The majority of the album was mixed prior to the recording, so after the smooth and fast vocal sessions, the album, Deep Beneath, was released in March 2008.</p>
		<p>It was also time to consider having all the full length albums released so far in CD format, in addition to the digital formats used so far. After dabbling a little bit with quotations and tweaking the orders, it was decided to go on with the CD manufacturing. In mid-June 2008, all full length albums became available on CD, and a worldwide distributor was found a bit later. After several different distributors and some unexpected events, the albums finally became available directly through the band website.</p>
		<p>As customary at this point, the songwriting process for the next full length album began very soon, in the heat of the summer 2008. This time the experience and flow brought an uncanny amount of songs to choose from. Ultimately 11 songs were completed throughout the year, allowing the recording process to come to life once more - not even one year after the previous one! Once more, records were broken in the time it took to get it all tracked, and thus it was time go on with writing the lyrics. This marked the first time for the band that a true concept album was written. As the title of the album tells, the lyrics dealt with Posthumanism - at what point will humans no longer be human? - and the idea was intertwined within a futuristic story of experimental medical research and human augmentation.</p>
		<p>Fast forward a few months, and thus Posthumanism was released in April 2009. This album is probably the fastest album from the band, taking the style to death metal extremes with a futuristic production aesthetic. The album would also be the first to have live performances related to the release. The active duo of Juha and Matti would bring the band for several shows around this time, proving that the sound will also work very well in a live setting.</p>
		<p>Something was brewing though, but that notwithstanding, the band continued to perform live and began the songwriting process in June 2009 to begin working on the next full length album - already the 5th one! This process would continue until the end of the year.</p>
	</section>
<h3 class="releaseTitleText">2010 - Now</h3>
	<section class="justified postText">
		<p>The year 2010 began in songwriting mode, with a few more songs left to do until another session in the studio would begin. Halfway through the sessions, there would be a show in Matti's native Oulu, where some of the new songs were performed live for the very first time, to a very keen audience. The final songs remaining to finalize the album were ready in April 2010, and thus the trusty guitar was dusted off once more to provide the much needed notes to the listening world. The session itself took place in the Liberty Street Studios for the last time, in mid-April 2010. All guitar and bass tracks were completed in record time, in just 3 days, and provided a solid layer to build the album upon. But unfortunately it would be a long time before the album would finally be released.</p>
		<p>While waiting for the vocals to be materialize, the remainder of the year took the band to performing their northmost show up in Rovaniemi - deep in Lapland - to an audience of exceptional extaticity! The show featured three brand new songs with very different lyrics from the final result, that would appear on the scene, surprisingly, a few years later. The end of the year was spent mixing the future album and an accompanying EP, the first since 2005. Eventually the EP, Infocalypse, would be released in December 2010, with complete vocals by Juha. The previous such release was of course the debut album, Conclusion. The EP was also a platform for a little bit of experimentation in clean vocals, new types of sounds and styles, and the first heavy vocals for Juha. In another interesting twist, Ville Miinala joined the band after a few successful rehearsal sessions in Kemi.</p>
		<p>But, coming back to the full length album, a few successful tracking sessions had taken place in Oulu with Matti on vocal duties. He had, unfortunately, become too preoccupied to bring the vocal recordings to a finish. After an extended period of time, it would come to pass that a new vocalist would join in to conclude the recording of vocals. And thus Mikko Nikula entered the picture. In a surprise twist, Ville also offered to record real drums for the album to be, and that's exactly what happened! In April 2012, it was finally time to release the long-postponed album, Devoid of Life! The reception was very good, and the album was downloaded over 1000 times from the official website in just one month! With a very good reception, it was a no-brainer to have the album also on factory pressed CD! And thus 500 copies of the CD were made and finally made available in October 2012.</p>
		<p>One might wonder what happened during the vocal-hiatus between early 2011 and mid-2012? Fear not, it was spent in working towards the next album in time. This time it would lead to a new approach in the style, with the vast majority of the songs being based on more electronic sounds and aesthetics, and pummeled with heavy guitars. This new method led to a big inspiration and eventually produced a total of 18 demo songs that would be appearing on the associated releases. A short-lived idea of making an electronic remix album of select songs from our past for our 10th anniversary was eventually scrapped in favour of new songs, but one song from those plans would make it to the new album.</p>
		<p>Much of summer 2013 was spent recording the instruments and vocals for the new album and EP. The album, The Occlusion, would feature 14 songs including the aforementioned remix track. The EP, Impenitence, will contain a 4-song mixture of a bit different and more melody-based songs. As the album The Occlusion was completed, it would be time to release it in early 2014. The time period has also featured several band rehearsals up in Kemi, with the eyes set on playing live once more! And this is where the band stands right now, ready to kick ass, and alive as usual!</p>
		<p>As of March 2014, the band has been recording new demos for the next full length album (working title "...of What Remains"), which is being aimed for a late 2014 or early 2015 release. The songs are once more in the familiar Industrial Death Metal style, and leaning even more than usual towards the extreme ends of Blackened style!</p>
	</section>